services:
  postgres:
    image: postgres:17-alpine
    container_name: remind-postgres
    environment:
      POSTGRES_DB: remind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - remind_postgres_data:/var/lib/postgresql/data

volumes:
  remind_postgres_data:
